/**
 * @file pkgbuild_writer.cpp
 * @brief PkgbuildWriter 实现
 *
 * 生成完全符合 AUR 规范的 PKGBUILD 文件。
 * 注意: 不使用 std::regex 和 std::istringstream (musl 静态链接兼容性)
 */

#include "pkgbuild_writer.h"
#include "core/executor.h"
#include "core/logger.h"

#include <fstream>
#include <sstream>
#include <ctime>
#include <iomanip>

namespace deb2pkg {

std::string PkgbuildWriter::EscapeBash(const std::string& str) {
    std::string result;
    for (char c : str) {
        if (c == '\'') {
            result += "'\\''";
        } else {
            result += c;
        }
    }
    return result;
}

std::string PkgbuildWriter::FormatBashArray(const std::vector<std::string>& items) {
    if (items.empty()) {
        return "()";
    }
    std::ostringstream oss;
    oss << "(";
    for (size_t i = 0; i < items.size(); i++) {
        if (i > 0) oss << " ";
        oss << "'" << EscapeBash(items[i]) << "'";
    }
    oss << ")";
    return oss.str();
}

std::string PkgbuildWriter::ComputeSha256(const std::filesystem::path& file_path) {
    Logger::Verbose("正在计算 SHA256 校验值： " + file_path.filename().string());

    auto result = Executor::RunCommand(
        {"sha256sum", file_path.string()},
        {},
        120
    );

    if (result.first && !result.second.empty()) {
        // 手动解析 "hash  filename\n" 格式
        auto space = result.second.find(' ');
        if (space != std::string::npos) {
            std::string hash = result.second.substr(0, space);
            if (!hash.empty()) {
                Logger::Verbose("  SHA256: " + hash);
                return hash;
            }
        }
    }

    Logger::Warning("无法计算 SHA256，请手动填写 sha256sums 字段");
    return "SKIP";
}

std::string PkgbuildWriter::Generate(const PackageInfo& info) {
    Logger::Info("正在生成 PKGBUILD...");
    
    std::ostringstream pkgbuild;

    // ---- 文件头注释 ----
    pkgbuild << "# Maintainer: Generated by deb2pkg\n";
    pkgbuild << "# 原始包: " << info.orig_name << "\n";
    pkgbuild << "# 原始格式: " << (info.type == PackageType::Deb ? "Debian" : "RPM") << "\n";

    // 当前时间
    auto now = std::time(nullptr);
    auto* tm = std::localtime(&now);
    pkgbuild << "# 生成时间: "
             << std::put_time(tm, "%Y-%m-%d %H:%M:%S") << "\n\n";

    // ---- 基本信息 ----
    pkgbuild << "pkgname=" << info.pkgname << "\n";
    pkgbuild << "pkgver=" << info.version << "\n";
    pkgbuild << "pkgrel=" << info.pkgrel << "\n\n";

    // ---- 描述 ----
    pkgbuild << "pkgdesc='" << EscapeBash(info.desc) << "'\n\n";

    // ---- 架构 ----
    pkgbuild << "arch=(" << info.arch << ")\n\n";

    // ---- 许可证 ----
    pkgbuild << "license=(" << info.license_str << ")\n\n";

    // ---- URL ----
    if (!info.url.empty()) {
        pkgbuild << "url='" << EscapeBash(info.url) << "'\n\n";
    }

    // ---- 依赖 ----
    if (!info.depends.empty()) {
        pkgbuild << "depends=" << FormatBashArray(info.depends) << "\n\n";
    } else {
        pkgbuild << "depends=()\n\n";
    }

    // ---- provides ----
    pkgbuild << "provides=('" << EscapeBash(info.orig_name) << "')\n\n";

    // ---- source ----
    std::string source_filename = info.source_path.filename().string();
    pkgbuild << "source=('" << EscapeBash(source_filename) << "')\n";

    // ---- sha256sums ----
    std::string sha256 = ComputeSha256(info.source_path);
    pkgbuild << "sha256sums=('" << sha256 << "')\n\n";

    // ---- makedepends ----
    if (info.type == PackageType::Deb) {
        pkgbuild << "makedepends=('binutils' 'libarchive')\n\n";
    } else {
        pkgbuild << "makedepends=('libarchive')\n\n";
    }

    // ---- 选项 ----
    pkgbuild << "options=(!strip !emptydirs)\n";
    pkgbuild << "install=${pkgname}.install\n\n";

    // ---- 未匹配依赖的注释 ----
    if (!info.unresolved.empty()) {
        pkgbuild << "# ============================================\n";
        pkgbuild << "# 警告：以下共享库未能自动匹配 Arch 包名\n";
        pkgbuild << "# 请手动在 depends 数组中添加对应包名\n";
        for (const auto& soname : info.unresolved) {
            pkgbuild << "#   " << soname << "\n";
        }
        pkgbuild << "# ============================================\n\n";
    }

    // ---- prepare() 函数 ----
    pkgbuild << "prepare() {\n";
    pkgbuild << "  cd \"${srcdir}\"\n";
    pkgbuild << "  mkdir -p data\n\n";

    if (info.type == PackageType::Deb) {
        pkgbuild << "  # 解压 Debian 包\n";
        pkgbuild << "  echo \"正在解压 " << EscapeBash(source_filename) << "...\"\n";
        pkgbuild << "  ar x \"" << EscapeBash(source_filename) << "\"\n";
        pkgbuild << "  local data_tar=$(ls data.tar.* 2>/dev/null | head -1)\n";
        pkgbuild << "  if [ -z \"$data_tar\" ]; then\n";
        pkgbuild << "    echo \"错误：未找到 data.tar.* 文件\"\n";
        pkgbuild << "    return 1\n";
        pkgbuild << "  fi\n";
        pkgbuild << "  bsdtar -xf \"$data_tar\" -C data/\n";
    } else {
        pkgbuild << "  # 解压 RPM 包\n";
        pkgbuild << "  echo \"正在解压 " << EscapeBash(source_filename) << "...\"\n";
        pkgbuild << "  bsdtar -xf \"" << EscapeBash(source_filename) << "\" -C data/\n";
    }

    pkgbuild << "\n";
    pkgbuild << "  # 修正跨发行版路径差异\n";
    pkgbuild << "  echo \"正在修正路径差异...\"\n";
    pkgbuild << "  fix_path() {\n";
    pkgbuild << "    local src=\"$1\" dst=\"$2\"\n";
    pkgbuild << "    if [ -d \"data/${src}\" ]; then\n";
    pkgbuild << "      mkdir -p \"data/${dst}\"\n";
    pkgbuild << "      find \"data/${src}\" -mindepth 1 -maxdepth 1 \\\n";
    pkgbuild << "        -exec mv -t \"data/${dst}\" {} \\; 2>/dev/null || true\n";
    pkgbuild << "      rmdir \"data/${src}\" 2>/dev/null || true\n";
    pkgbuild << "    fi\n";
    pkgbuild << "  }\n";
    pkgbuild << "\n";
    pkgbuild << "  for arch_dir in x86_64-linux-gnu i386-linux-gnu i686-linux-gnu \\\n";
    pkgbuild << "                   aarch64-linux-gnu arm-linux-gnueabihf arm-linux-gnueabi \\\n";
    pkgbuild << "                   powerpc64le-linux-gnu s390x-linux-gnu; do\n";
    pkgbuild << "    fix_path \"usr/lib/${arch_dir}\" \"usr/lib\"\n";
    pkgbuild << "    fix_path \"lib/${arch_dir}\" \"usr/lib\"\n";
    pkgbuild << "  done\n";
    pkgbuild << "\n";
    pkgbuild << "  fix_path \"lib64\" \"usr/lib\"\n";
    pkgbuild << "  fix_path \"usr/lib64\" \"usr/lib\"\n";
    pkgbuild << "\n";
    pkgbuild << "  rm -f control.tar.* data.tar.* debian-binary 2>/dev/null || true\n";
    pkgbuild << "}\n\n";

    // ---- package() 函数 ----
    pkgbuild << "package() {\n";
    pkgbuild << "  cd \"${srcdir}\"\n\n";
    pkgbuild << "  if [ -d \"data\" ]; then\n";
    pkgbuild << "    cp -r --no-preserve=ownership data/* \"${pkgdir}/\"\n";
    pkgbuild << "  else\n";
    pkgbuild << "    echo \"错误：未找到 data/ 目录\"\n";
    pkgbuild << "    return 1\n";
    pkgbuild << "  fi\n\n";
    pkgbuild << "  rm -rf \"${pkgdir}/usr/lib/x86_64-linux-gnu\" 2>/dev/null || true\n";
    pkgbuild << "  rm -rf \"${pkgdir}/usr/lib/i386-linux-gnu\" 2>/dev/null || true\n";
    pkgbuild << "  rm -rf \"${pkgdir}/usr/lib/aarch64-linux-gnu\" 2>/dev/null || true\n";
    pkgbuild << "  rm -rf \"${pkgdir}/usr/lib64\" 2>/dev/null || true\n";
    pkgbuild << "  rm -rf \"${pkgdir}/lib64\" 2>/dev/null || true\n";
    pkgbuild << "  rm -rf \"${pkgdir}/lib/x86_64-linux-gnu\" 2>/dev/null || true\n\n";
    pkgbuild << "  if [ -d \"${pkgdir}/lib/systemd\" ] && [ ! -d \"${pkgdir}/usr/lib/systemd\" ]; then\n";
    pkgbuild << "    mkdir -p \"${pkgdir}/usr/lib\"\n";
    pkgbuild << "    mv \"${pkgdir}/lib/systemd\" \"${pkgdir}/usr/lib/systemd\"\n";
    pkgbuild << "  fi\n";
    pkgbuild << "}\n";

    return pkgbuild.str();
}

std::string PkgbuildWriter::GenerateInstallScript() {
    std::ostringstream script;
    script << "# 安装/卸载钩子 — 刷新桌面和图标缓存\n\n";
    script << "post_install() {\n";
    script << "  if command -v update-desktop-database &>/dev/null; then\n";
    script << "    update-desktop-database -q\n";
    script << "  fi\n";
    script << "  if command -v gtk-update-icon-cache &>/dev/null; then\n";
    script << "    for dir in usr/share/icons/hicolor usr/share/icons/HighContrast \\\n";
    script << "               usr/share/icons/locolor usr/share/icons/gnome; do\n";
    script << "      if [ -d \"${dir}\" ]; then\n";
    script << "        gtk-update-icon-cache -q -t -f \"${dir}\" 2>/dev/null || true\n";
    script << "      fi\n";
    script << "    done\n";
    script << "  fi\n";
    script << "  if command -v update-mime-database &>/dev/null; then\n";
    script << "    update-mime-database usr/share/mime 2>/dev/null || true\n";
    script << "  fi\n";
    script << "}\n\n";
    script << "post_upgrade() {\n";
    script << "  post_install\n";
    script << "}\n\n";
    script << "post_remove() {\n";
    script << "  post_install\n";
    script << "}\n";
    return script.str();
}

std::filesystem::path PkgbuildWriter::WriteToFile(
    const std::string& content,
    const std::filesystem::path& output_dir,
    const std::string& pkgname)
{
    std::filesystem::path pkg_dir = output_dir / pkgname;
    std::error_code ec;
    std::filesystem::create_directories(pkg_dir, ec);

    if (ec) {
        Logger::Error("无法创建输出目录：" + pkg_dir.string(),
                      "请检查目录写入权限：ls -ld " + output_dir.string());
        return {};
    }

    std::filesystem::path pkgbuild_path = pkg_dir / "PKGBUILD";
    std::ofstream file(pkgbuild_path);
    if (!file) {
        Logger::Error("无法写入 PKGBUILD 文件：" + pkgbuild_path.string(),
                      "请检查磁盘空间和目录权限");
        return {};
    }

    file << content;
    file.close();

    // 写入 .install 安装脚本
    std::filesystem::path install_path = pkg_dir / (pkgname + ".install");
    std::ofstream install_file(install_path);
    if (install_file) {
        install_file << GenerateInstallScript();
        install_file.close();
        Logger::Verbose(".install 文件已生成：" + install_path.string());
    }

    Logger::Success("PKGBUILD 已生成：" + pkgbuild_path.string());
    return pkgbuild_path;
}

} // namespace deb2pkg
